-- OEPEDTSWP_SEED
-- Seed rows for AIRRELCTL's control-file-driven channel list (OEPEDTSWP).
--
-- The first two rows reproduce AIRRELCTL's old hardcoded IN-list (Mirakl
-- EDI and Amazon.com Note). The rest are the additional "pure stamping"
-- channels named in the ticket for options 7/8.
--
-- To add a channel later: INSERT one row with ACTIVE = 'Y'.
-- To stop sweeping a channel: UPDATE its row to ACTIVE = 'N' (or delete it).
-- The DESC value must match OEPBCHK.DESC20 exactly (case-insensitive,
-- trailing blanks ignored).

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('MIRAKL EDI', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('AMAZON.COM NOTE', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('MUSIC SALES ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('SMD.COM APP ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('HL DGT BOOKS ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('MUSIC SALES CREDIT', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('ARRANGEME DGT ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('DIGITAL RTL ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('DIGITAL RTL CREDIT', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('MD CONSUMER ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('HL DGT BOOKS CREDIT', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('MODERN DRUMMER', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('ARRANGEME DGT CREDIT', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('MUSIC DIRECT ORDERS', 'Y');

INSERT INTO OEPEDTSWP (DESC, ACTIVE)
  VALUES ('TRW EDI', 'Y');
